export const INTERESTS = [
  "AI/ML",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Cybersecurity",
  "Data Science",
  "Game Development",
  "Open Source",
  "Blockchain",
  "Cloud Computing",
  "DevOps",
  "Product Design",
  "Robotics",
  "Automation",
  "Creative Coding",
  "Graphic Design",
  "3D Modeling",
  "Research",
  "Entrepreneurship",
  "Startups",
  "Public Speaking",
  "Writing",
  "Teaching",
  "Gaming",
  "Math",
] as const;

export type Interest = (typeof INTERESTS)[number];
