name: Build Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - staging
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js with Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build application
        env:
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          CONVEX_DEPLOYMENT: ${{ vars.CONVEX_DEPLOYMENT }}
          CONVEX_DEPLOY_KEY: ${{ vars.CONVEX_DEPLOY_KEY }}
          SITE_URL: ${{ vars.SITE_URL }}
          NEXT_PUBLIC_CONVEX_URL: ${{ vars.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_CONVEX_SITE_URL: ${{ vars.NEXT_PUBLIC_CONVEX_SITE_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
        run: bun run build:ci
